### ISSUE TITLE
Many warnings

### ISSUE THREAD

**Issue by Cthutu** [yhirose/cpp-linenoise#13]
Building on a MS compiler gives many warnings related to conversions between size_t and int, and similar.  On a build that forces warnings to be errors, this was a problem.  I had to patch the source code to do the casts.

**Comment by yhirose** [comment]
@Cthutu, thanks for the report. Which version of VC++ are you using?

I have just tested on the latest VC++ 2017. I got only two warnings when I compiled linenoise.hpp with example.cpp in the example folder.

```
2>example.cpp
2>d:\dropbox\projects\cpp-linenoise\example\../linenoise.hpp(1695): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt\stdio.h(2260): note: see declaration of 'sscanf'
2>d:\dropbox\projects\cpp-linenoise\example\../linenoise.hpp(2041): warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt\string.h(136): note: see declaration of 'strcpy'
2>example.vcxproj -> D:\Dropbox\Projects\cpp-linenoise\example\build.win\Debug\example.exe
2>example.vcxproj -> D:/Dropbox/Projects/cpp-linenoise/example/build.win/Debug/example.pdb (Full PDB)
2>Done building project "example.vcxproj".```

**Comment by Cthutu** [comment]
2017

**Comment by yhirose** [comment]
@Cthutu, since I didn't get the conversion problem between size_t and int with my VC 2017, I need more information to handle it. Is it possible for you to send a pull request that has the patch you mentioned in your first comment?

**Comment by Cthutu** [comment]
Hi always build in 64-bit so maybe in 32-bit builds you don't get it.  If
that isn't enough information then I will set up a fork to create a pull
request.

**Comment by yhirose** [comment]
Thanks for the clue. I am now able to see lots of warnings!

**Comment by yhirose** [comment]
@Cthutu I fixed the issue. Only remaining warnings are related to non-secure CRT functions such as sscanf and strcpy.
Please let me know if you still have the 'many warnings' problem.
Thanks for your help!
