### ISSUE TITLE
Move to C implementation ?

### ISSUE THREAD

**Issue by nojb** [yhirose/cpp-linenoise#14]
I think this is a great project but personally the use of C++ is a deal-breaker for me.

What is the dependency of `cpp-linenoise` on `C++` ? Have you considered switching to `C` ?

**Comment by yhirose** [comment]
@nojb thank you for your thought. I have not considered switching to C.

The reason why I use C++ is that I need "header-only" library, C doesn't have ability to make header-only library, and it always requires `.c` file.

If you want a C-based library, you can consider to use the original linenoise (https://github.com/antirez/linenoise) which is written in C. If you need UTF-8 encoding support, you may be interested in my fork (https://github.com/yhirose/linenoise/tree/utf8-support). Unfortunately though, both don't give us Windows support...

**Comment by nojb** [comment]
Thanks for your reply!

**Comment by LoganDark** [comment]
@yhirose if you ever do consider "switching" to C, please maintain this version as well, because good header-only libraries are a rarity these days. :>

**Comment by yhirose** [comment]
@LoganDark, thanks for your input. Yes, I am not going away from the C++ head-only approach.
