### ISSUE TITLE
Clean up C++11 warnings?

### ISSUE THREAD

**Issue by wrlear** [yhirose/cpp-linenoise#21]
cpp-linenoise.hpp builds and runs on C++11 compilers, but -Wall produces many warnings - implicit signed/unsigned conversions, old style casts, deprecated functions (sscanf),  goto crossing a variable initialization. The goto issue is actually considered fatal in gcc unless -fpermissive is specified.

Any thoughts about updating the source?

**Comment by yhirose** [comment]
@wrlear, thanks for the feedback. As you can see the statement in README, cpp-linenoise "gathered code from following excellent libraries, clean it up, and put it into a C++ header file for convenience."
I would like to keep the cpp-linenoise code as close to the original source libraries as possible. If they fix the warnings, I would gladly merge the changes to cpp-linenoise.
