### ISSUE TITLE
mingw + msys build failure

### ISSUE THREAD

**Issue by michael-herwig** [yhirose/cpp-linenoise#24]
Hi there,

I am currently porting this library to hunter (a cmake based package manger) and encountered build errors using mingw and msys.

Build logs can be found here:
- [mingw](https://ci.appveyor.com/project/michael-herwig/hunter/builds/28530341/job/vjg8s9d13kx5eu3w)
- [msys](https://ci.appveyor.com/project/michael-herwig/hunter/builds/28530341/job/3xvlp48cvhyievwc)

Regards
Michael

**Comment by yhirose** [comment]
@michael-herwig, thanks for the feedback. As you can see the statement in README, cpp-linenoise "gathered code from following excellent libraries, clean it up, and put it into a C++ header file for convenience."
I would like to keep the cpp-linenoise code as close to the original source libraries as possible. If they fix the warnings, I would gladly merge the changes to cpp-linenoise.

**Comment by michael-herwig** [comment]
@yhirose thanks for the response. Are you sure it's from linenoise? I just had a look at the mingw [error line](https://github.com/yhirose/cpp-linenoise/blob/master/linenoise.hpp#L1651) and comparing [this method](https://github.com/yhirose/cpp-linenoise/blob/master/linenoise.hpp#L1595-L1674) to [linenoise](https://github.com/antirez/linenoise/blob/master/linenoise.c#L218) it looks like the windows version is patched into it and is not from linenoise.

**Comment by yhirose** [comment]
As you can see in README, this library code is from the following libraries:

 - linenoise.h and linenose.c (https://github.com/antirez/linenoise)
 - ANSI.c (https://github.com/adoxa/ansicon)
 - Win32_ANSI.h and Win32_ANSI.c (https://github.com/MSOpenTech/redis)

Basically, I didn't touch their implementations, rather just put them into a .hpp file as a C++ header-only library for my convenience.

linenoise itself still doesn't support Windows. (It doesn't support Unicode either.)
You can check the current status of the Windows support in linenoise here.
https://github.com/antirez/linenoise/issues/113

You many also want to consider to use this library:
https://github.com/arangodb/linenoise-ng

Hope it helps,

**Comment by chfanghr** [comment]
I ran into the same issue and I make a patch to fix it.
[link](https://github.com/chfanghr/calculator/blob/master/cmd/calc/third_party/cpp_linenoise_patch_mingw.patch)
