### ISSUE TITLE
Tab gets appended after auto-completion

### ISSUE THREAD

**Issue by sytelus** [yhirose/cpp-linenoise#3]
Just saw this bug... 

Repro steps:
1. Setup linenoise with few autocomplete.
2. Press first char, press Tab to do auto complete.
3. Press space.

Notice that tab gets appended in console. if you try to do backspace, you get weird behavior now.

**Comment by yhirose** [comment]
@sytelus, thanks for the bug report. I fixed it at 0fb923f0a5a9fcb2c03a9d3781a2748f8bf699a0.
Could you confirm it's fixed on your environment?
