### ISSUE TITLE
Compiler errors with -Wall

### ISSUE THREAD

**Issue by sytelus** [yhirose/cpp-linenoise#4]
I'm compiling everything with all warnings as errors (it's just good practice). On GCC linenoise has one warning and doesn't compile:

```
.../include/linenoise.hpp:1826:12: warning: unused variable ‘plen’ [-Wunused-variable]
     size_t plen = l->prompt.length();

```

**Comment by yhirose** [comment]
Thanks for the report. I'll take a care of it.
