### ISSUE TITLE
Visual Studio 2015 Compile Error 

### ISSUE THREAD

**Issue by severila** [yhirose/cpp-linenoise#5]
Compiling with VS2015 gives me this error:
`Severity    Code    Description Project File
Error   C2664   'int linenoise::win32read(int *)': cannot convert argument 1 from 'int **' to 'int *'`

Changing line 1802 from 
`nread = win32read(&c);`
to 
`nread = win32read(c);`
solves the issue for me.

I'm not familiar with your code, so not sure if this makes sense.

**Comment by yhirose** [comment]
@severila, you are totally correct! Thanks for the report.
